import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Portfolio",
	description: "Generated by create next app",
};

export default function PortfolioLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="bg-blue-50">
			<div className="mx-auto min-h-screen max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-16 lg:py-0 ">
				{children}
			</div>
		</div>
	);
}
